CREATE TABLE CUSTOMERS (
CUSTOMER_ID INT, 
CUST_FIRST_NAME VARCHAR(40), 
CUST_LAST_NAME VARCHAR(40), 
NLS_LANGUAGE VARCHAR(3), 
NLS_TERRITORY VARCHAR(50), 
CREDIT_LIMIT INT, 
CUST_EMAIL VARCHAR(100), 
ACCOUNT_MGR_ID INT, 
CUSTOMER_SINCE DATE, 
CUSTOMER_CLASS VARCHAR(40), 
SUGGESTIONS VARCHAR(40), 
DOB DATE, 
MAILSHOT VARCHAR(1), 
PARTNER_MAILSHOT VARCHAR(1), 
PREFERRED_ADDRESS INT, 
PREFERRED_CARD INT,
START_BATCH INT,
END_BATCH INT,
UNIQUE(CUSTOMER_ID)
);

CREATE TABLE LOGON 
(	
LOGON_ID NUMERIC, 
CUSTOMER_ID NUMERIC, 
LOGON_DATE DATE,
UNIQUE(LOGON_ID)
);

CREATE TABLE ORDERS
(ORDER_ID NUMERIC(12,0) , 
ORDER_DATE TIMESTAMP, 
ORDER_MODE VARCHAR(8), 
CUSTOMER_ID NUMERIC(12,0) NOT NULL, 
ORDER_STATUS NUMERIC(2,0), 
ORDER_TOTAL NUMERIC(8,2), 
SALES_REP_ID NUMERIC(6,0), 
PROMOTION_ID NUMERIC(6,0), 
WAREHOUSE_ID NUMERIC(6,0), 
DELIVERY_TYPE VARCHAR(15), 
COST_OF_DELIVERY NUMERIC(6,0), 
WAIT_TILL_ALL_AVAILABLE VARCHAR(15), 
DELIVERY_ADDRESS_ID NUMERIC(12,0), 
CUSTOMER_CLASS VARCHAR(30), 
CARD_ID NUMERIC(12,0), 
INVOICE_ADDRESS_ID NUMERIC(12,0), 
UNIQUE(ORDER_ID)
)


CREATE TABLE DEMO
(	ID NUMERIC, 
	NAME VARCHAR2(200)
);